package view;

public enum PanelState {
	BOARD_STATE_UNCERTAIN,
	BOARD_MENU_SHOWN,
	BOARD_WAIT_FOR_MOVE,
	BOARD_WAITING_FOR_ATTACK,
	BOARD_WAIT_ACTION,
	BOARD_START_NEW_TURN,
	BOARD_STATE_MENU_SHOWN,
	BOARD_NO_MENU_SHOWN,
	
	PIECE_NON_CHOSEN,
	PIECE_CHOSEN,
	SQUARE_EMPTY,
	SQUARE_MOVABLE,
	SQUARE_ATTACKABLE, ITEM_UNVISITED,  
}
